import { Metadata } from "next";
import Layout from "../components/Layout/Layout";
import "./globals.css";
import AuthContextProvider from "../context/AuthContext";

export const metadata: Metadata = {
  title: {
    default: "OpenTable",
    template: "%s | OpenTable",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body>
        <AuthContextProvider>
          <Layout>{children}</Layout>
        </AuthContextProvider>
      </body>
    </html>
  );
}
